### PR TITLE
lec3 comments

### PR DESCRIPTION
**Pull request by Keminyung**
@WuChangJin94 @leowang707

### CODE REVIEW

**Comment by leowang707** [comment]
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu/tests/team_7, configfile: pytest.ini
plugins: anyio-3.6.2
collected 7 items                                                              

tests/team_7/lec3/test_city_planner.py F                                 [ 14%]
tests/team_7/lec3/test_digraph.py .xx...                                 [100%]

=================================== FAILURES ===================================
______________________________ test_city_planner _______________________________

    def test_city_planner():
    
        # Create an instance of CityPlanner
>       cp = CityPlanner()
E       NameError: name 'CityPlanner' is not defined

tests/team_7/lec3/test_city_planner.py:8: NameError
=========================== short test summary info ============================
FAILED tests/team_7/lec3/test_city_planner.py::test_city_planner - NameError:...
==================== 1 failed, 4 passed, 2 xfailed in 0.07s ====================

**Comment by leowang707** [comment]
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu/tests/team_7, configfile: pytest.ini
plugins: anyio-3.6.2
collected 7 items                                                              

tests/team_7/lec3/test_city_planner.py F                                 [ 14%]
tests/team_7/lec3/test_digraph.py .xx...                                 [100%]

=================================== FAILURES ===================================
______________________________ test_city_planner _______________________________

    def test_city_planner():
        # Create an instance of CityPlanner
>       cp = CityPlanner()
E       NameError: name 'CityPlanner' is not defined

tests/team_7/lec3/test_city_planner.py:6: NameError
=============================== warnings summary ===============================
../../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1249
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1249: PytestConfigWarning: Unknown config option: 
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/team_7/lec3/test_city_planner.py::test_city_planner - NameError:...
============== 1 failed, 4 passed, 2 xfailed, 1 warning in 0.08s ===============

**Comment by leowang707** [comment]
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu/tests/team_7, configfile: pytest.ini
plugins: anyio-3.6.2
collected 7 items                                                              

tests/team_7/lec3/test_city_planner.py F                                 [ 14%]
tests/team_7/lec3/test_digraph.py .xx...                                 [100%]

=================================== FAILURES ===================================
______________________________ test_city_planner _______________________________

    def test_city_planner():
    
>       cp = CityPlanner()
E       NameError: name 'CityPlanner' is not defined

tests/team_7/lec3/test_city_planner.py:3: NameError
=============================== warnings summary ===============================
../../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1249
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1249: PytestConfigWarning: Unknown config option: 
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/team_7/lec3/test_city_planner.py::test_city_planner - NameError:...
============== 1 failed, 4 passed, 2 xfailed, 1 warning in 0.07s ===============

**Comment by Keminyung** [comment]
@WuChangJin94 @leowang707

**Comment by leowang707** [comment]
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu/tests/team_7, configfile: pytest.ini
plugins: anyio-3.6.2
collected 17 items / 1 error / 1 deselected / 15 selected                      

==================================== ERRORS ====================================
__________________ ERROR collecting lec3/test_city_planner.py __________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_7/lec3/test_city_planner.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/team_7/lec3/test_city_planner.py:1: in <module>
    from lecture3_graph import CityPlanner
E   ImportError: cannot import name 'CityPlanner' from 'lecture3_graph' (/home/arg/oop-python-nycu/tests/team_7/lec3/lecture3_graph.py)
=============================== warnings summary ===============================
../../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1249
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1249: PytestConfigWarning: Unknown config option: 
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR tests/team_7/lec3/test_city_planner.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
================== 1 deselected, 1 warning, 1 error in 0.06s ===================

**Comment by Keminyung** [comment]
@WuChangJin94 @leowang707

**Comment by leowang707** [comment]
好像放錯了，這是助教課的檔案，請修正或移除
tests/team_7/lec4/lecture4.py

**Comment by Keminyung** [comment]
@WuChangJin94 @leowang707

**Pull request merged**
