### PR TITLE
add testing and docstring

### PR DESCRIPTION
**Pull request by chienyichieh**
@wennnny @WuChangJin94

### CODE REVIEW

**Comment by WuChangJin94** [comment]
root@D830MT:~/oop-python-nycu# pytest tests/team_5/
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu
plugins: xdoctest-1.1.2, profiling-1.7.0, anyio-3.6.2
collected 8 items / 2 errors / 6 selected                                      

==================================== ERRORS ====================================
______________ ERROR collecting tests/team_5/test_city_planner.py ______________
/usr/local/lib/python3.8/dist-packages/_pytest/python.py:599: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/usr/local/lib/python3.8/dist-packages/_pytest/pathlib.py:533: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/usr/local/lib/python3.8/dist-packages/_pytest/assertion/rewrite.py:171: in exec_module
    exec(co, module.__dict__)
tests/team_5/test_city_planner.py:2: in <module>
    from lecture3_graph import *
E     File "/home/arg/oop-python-nycu/tests/team_5/lecture3_graph.py", line 18
E       def get_name(self):
E       ^
E   IndentationError: unexpected indent
________________ ERROR collecting tests/team_5/test_digraph.py _________________
/usr/local/lib/python3.8/dist-packages/_pytest/python.py:599: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/usr/local/lib/python3.8/dist-packages/_pytest/pathlib.py:533: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
/usr/local/lib/python3.8/dist-packages/_pytest/assertion/rewrite.py:171: in exec_module
    exec(co, module.__dict__)
tests/team_5/test_digraph.py:2: in <module>
    from lecture3_graph import *
E     File "/home/arg/oop-python-nycu/tests/team_5/lecture3_graph.py", line 18
E       def get_name(self):
E       ^
E   IndentationError: unexpected indent
=========================== short test summary info ============================
ERROR tests/team_5/test_city_planner.py
ERROR tests/team_5/test_digraph.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 0.14s ===============================

**Comment by WuChangJin94** [comment]
The following portion passed
root@D830MT:~/oop-python-nycu# pytest tests/test_lec10_complexity_part1.py 
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu
plugins: xdoctest-1.1.2, profiling-1.7.0, anyio-3.6.2
collected 93 items                                                             

tests/test_lec10_complexity_part1.py ................................... [ 37%]
..........................................................                               [100%]

===================================== 93 passed in 50.09s ======================================
however, previous issue within team_5 folder still fails

**Comment by PinYenChen** [comment]
@WuChangJin94 @leowang707 dear TAs we have fixed the file of team5

**Comment by leowang707** [comment]
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu
plugins: anyio-3.6.2
collected 22 items                                                             

tests/team_5/test_city_planner.py .                                      [  4%]
tests/team_5/test_digraph.py ....                                        [ 22%]
tests/team_5/test_food.py FFFF....                                       [ 59%]
tests/team_5/test_lec4.py .........                                      [100%]

=================================== FAILURES ===================================
________________________________ test_get_value ________________________________

food = <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf52e0>

    def test_get_value(food):
>       assert food.get_value() == 100
E       assert 20 == 100
E        +  where 20 = <bound method Food.get_value of <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf52e0>>()
E        +    where <bound method Food.get_value of <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf52e0>> = <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf52e0>.get_value

tests/team_5/test_food.py:41: AssertionError
________________________________ test_get_cost _________________________________

food = <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf5af0>

    def test_get_cost(food):
>       assert food.get_cost() == 50
E       assert 40 == 50
E        +  where 40 = <bound method Food.get_cost of <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf5af0>>()
E        +    where <bound method Food.get_cost of <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf5af0>> = <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf5af0>.get_cost

tests/team_5/test_food.py:44: AssertionError
_________________________________ test_density _________________________________

food = <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf5d60>

    def test_density(food):
>       assert food.density() == 2
E       assert 0.5 == 2
E        +  where 0.5 = <bound method Food.density of <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf5d60>>()
E        +    where <bound method Food.density of <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf5d60>> = <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90bf5d60>.density

tests/team_5/test_food.py:47: AssertionError
___________________________________ test_str ___________________________________

food = <mit_ocw_data_science.lec2.menu.Food object at 0x7f5e90c12280>

    def test_str(food):
>       assert str(food) == "papaya: <100, 50>"
E       AssertionError: assert 'orange: <20, 40>' == 'papaya: <100, 50>'
E         - papaya: <100, 50>
E         + orange: <20, 40>

tests/team_5/test_food.py:50: AssertionError
=========================== short test summary info ============================
FAILED tests/team_5/test_food.py::test_get_value - assert 20 == 100
FAILED tests/team_5/test_food.py::test_get_cost - assert 40 == 50
FAILED tests/team_5/test_food.py::test_density - assert 0.5 == 2
FAILED tests/team_5/test_food.py::test_str - AssertionError: assert 'orange: ...
========================= 4 failed, 18 passed in 1.84s =========================

**Comment by PinYenChen** [comment]
@WuChangJin94 @leowang707 dear TAs, I have fixed the problems in test_food.py!

**Pull request merged**
