### PR TITLE
Add folder test_food.py

### PR DESCRIPTION
**Pull request by PulsarGlory**
@yutingk @sunfu-chou

### CODE REVIEW

**Comment by sunfu-chou** [comment]
You might have forgotten to push add_path.py
image

**Comment by PulsarGlory** [comment]
@sunfu-chou @yutingk already push add_path.py

**Comment by sunfu-chou** [comment]
`test_lecture_6.py` should not be placed in your team folder. Please remove it.

**Comment by PulsarGlory** [comment]
@sunfu-chou

**Pull request merged**
