### PR TITLE
Update test_lec5_tuple.py

### PR DESCRIPTION
**Pull request by reb33340**
Are we required to commit only the testing code, or do we need to commit anything else? 
Sorry, I don't quite understand.

### CODE REVIEW

**Comment by hchengwang** [comment]
________________________________________________________ test_sum_elem_method1 ________________________________________________________

    def test_sum_elem_method1():
>       assert sum_elem_method1([1, 2, 3, 4]) == 10
E       NameError: name 'sum_elem_method1' is not defined

test_lec5_tuple.py:15: NameError
________________________________________________________ test_sum_elem_method2 ________________________________________________________

    def test_sum_elem_method2():
>       assert sum_elem_method2([1, 2, 3, 4]) == 10
E       NameError: name 'sum_elem_method2' is not defined

test_lec5_tuple.py:23: NameError
======================================================= short test summary info =======================================================
FAILED test_lec5_tuple.py::test_sum_elem_method1 - NameError: name 'sum_elem_method1' is not defined
FAILED test_lec5_tuple.py::test_sum_elem_method2 - NameError: name 'sum_elem_method2' is not defined

**Comment by hchengwang** [comment]
Essentially you need to commit code of your functions like sum_elem_method1. Is it in the src/mit_ocw_exercises/lec5_tuples_lists.py?

**Comment by reb33340** [comment]
sorry, I will change my code

**Comment by uwe77** [comment]
I've test the test_lec5_tuple.py, and it has 3 pass in 0.18s.
And new a branch call: Update_test_lec5_tuple_ID28.

**Pull request merged**
