### PR TITLE
Group 7 - Lecture 12

### PR DESCRIPTION
**Pull request by lyj87**
Add kinds of sorting algorithms.
@uwe77 @phoebeliu123 @zhuchi76 @wennnny @Brian2074 @AdamShih27 @JoshHuang666

### CODE REVIEW

**Comment by zhuchi76** [comment]
Please refer [other group](https://github.com/ARG-NCTU/oop-python-nycu/tree/main/tests/group3) to add pytest code.

**Comment by zhuchi76** [comment]
Please notice my comment plz.

**Comment by lyj87** [comment]
@zhuchi76 我們剛剛加了，麻煩幫我們看一下！

**Comment by zhuchi76** [comment]
Please sync your PR. Please do not put another file outside tests folder.
Your code: oop-python-nycu/tests/group7/test_sorting_043.py
occurs the error:

root@tzuchichen:~/oop-python-nycu/tests/group7# pytest test_sorting_043.py 
========================================= test session starts ==========================================
platform linux -- Python 3.8.10, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/arg/oop-python-nycu/tests/group7
plugins: anyio-4.4.0
collected 4 items                                                                                      

test_sorting_043.py E.F.                                                                         [100%]

================================================ ERRORS ================================================
_______________________________ ERROR at setup of test_sorting_algorithm _______________________________
file /home/arg/oop-python-nycu/tests/group7/test_sorting_043.py, line 20
  def test_sorting_algorithm(algorithm, test_cases):
E       fixture 'algorithm' not found
>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/home/arg/oop-python-nycu/tests/group7/test_sorting_043.py:20
=============================================== FAILURES ===============================================
_________________________________________ test_insertion_sort __________________________________________

    def test_insertion_sort():
>       test_sorting_algorithm(insertion_sort, test_cases)

test_sorting_043.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

algorithm = <function insertion_sort at 0x7eda9e422a60>
test_cases = {'all_same_elements': [5, 5, 5, 5, 5], 'empty_list': [], 'list_with_duplicates': [4, 7, 7, 8, 7, 6], 'list_with_negatives': [4, -10, 1, -9, 7, 2], ...}

    def test_sorting_algorithm(algorithm, test_cases):
        for name, data in test_cases.items():
            if name == "random_input":
                start_time = time.time()
                sorted_output = algorithm(data.copy())
                end_time = time.time()
>               assert sorted_output == sorted(data)
E               assert [0, 1, 3, 5, 6, 7, ...] == [0, 1, 3, 5, 6, 7, ...]
E                 
E                 At index 263 diff: 267 != 264
E                 Use -v to get more diff

test_sorting_043.py:26: AssertionError
----------------------------------------- Captured stdout call -----------------------------------------
Test passed for insertion_sort with empty_list
Test passed for insertion_sort with sorted_list
Test passed for insertion_sort with reverse_sorted_list
Test passed for insertion_sort with unsorted_list
Test passed for insertion_sort with list_with_duplicates
Test passed for insertion_sort with list_with_negatives
Test passed for insertion_sort with single_element_list
Test passed for insertion_sort with all_same_elements
======================================= short test summary info ========================================
FAILED test_sorting_043.py::test_insertion_sort - assert [0, 1, 3, 5, 6, 7, ...] == [0, 1, 3, 5, 6, 7, ...]
ERROR test_sorting_043.py::test_sorting_algorithm
================================= 1 failed, 2 passed, 1 error in 0.12s =================================
root@tzuchichen:~/oop-python-nycu/tests/group7#

**Pull request merged**
