### PR TITLE
group4 lec8

### PR DESCRIPTION
**Pull request by dylan7844**
changed function name

### CODE REVIEW

**Comment by uwe77** [comment]
pytest passed, but you shoudn't change the original code.
Please copy or new function to finish the task.

**Comment by dylan7844** [comment]
> pytest passed, but you shoudn't change the original code. Please copy or new function to finish the task.

change already with new file test_lec8_group4.py

**Comment by uwe77** [comment]
Please put changes in the same file"test_lec8_classes.py".

**Comment by dylan7844** [comment]
> Please put changes in the same file"test_lec8_classes.py". And make sure your branch is update to main branch.

already changed

**Comment by uwe77** [comment]
I've remove tests/test_lec8_group4.py, please remanber to delete extra file before PR next time.

**Pull request merged**
