### PR TITLE
Update test_lec6_recursion_dictionaries.py

### PR DESCRIPTION
**Pull request by cookieeikooc**

### CODE REVIEW

**Comment by hchengwang** [comment]
_______________________________________________________ test_most_common_words ________________________________________________________

    def test_most_common_words():
>       assert lec6.most_common_words(beatles) == ('yeah', 28)
E       NameError: name 'beatles' is not defined

test_lec6_recursion_dictionaries.py:28: NameError
======================================================= short test summary info =======================================================
FAILED test_lec6_recursion_dictionaries.py::test_most_common_words - NameError: name 'beatles' is not defined

**Comment by uwe77** [comment]
test_lec6_recursion_dictionaries.py failed at:
def test_most_common_words():
>       assert lec6.most_common_words(beatles) == ('yeah', 28)
E       NameError: name 'beatles' is not defined

Please modify your code and push at the branch call: Update_test_lec6_recursion_dictionaries_ID27

**Review by uwe77 — APPROVED** [review]
There was a missing line "assert lec6.is_palindrome('eillie') == True" on 26, I've solved the conflict this time, please update your repo first by pulling branch: main next time.

**Comment by uwe77** [comment]
test_lec6_recursion_dictionaries.py ..F                                  [100%]

=================================== FAILURES ===================================
____________________________ test_most_common_words ____________________________

    def test_most_common_words():
>       assert lec6.most_common_words(beatles) == ('yeah', 28)
E       NameError: name 'beatles' is not defined

test_lec6_recursion_dictionaries.py:29: NameError
=========================== short test summary info ============================
FAILED test_lec6_recursion_dictionaries.py::test_most_common_words - NameErro...
========================= 1 failed, 2 passed in 0.36s ==========================

There's still have a failed.

**Pull request closed without merging**
