### PR TITLE
Update tests/ lec5 , lec6, lec8

### PR DESCRIPTION
**Pull request by cookieeikooc**

### CODE REVIEW

**Comment by uwe77** [comment]
pytest failed at ...
test_lec6_recursion_dictionaries.py::test_fib PASSED
test_lec6_recursion_dictionaries.py::test_is_palindrome PASSED
test_lec6_recursion_dictionaries.py::test_most_common_words FAILED

**Comment by uwe77** [comment]
Also please use `git rm` to remove "myname.txt".

**Comment by cookieeikooc** [comment]
助教請問我如果remove myname.txt git push之後需要再發一次PR嗎？

**Comment by cookieeikooc** [comment]
還有請問可以跳過”[d094011](https://github.com/ARG-NCTU/oop-python-nycu/pull/55/commits/d0940116f51842a98d74c2fd0608e300c125f7a6)“嗎  前面我不太確定為什麼我已經update branch了之前的commit還是在😵‍💫 這樣應該most common words就會過了？

**Comment by cookieeikooc** [comment]
@uwe77 再麻煩助教了

**Comment by cookieeikooc** [comment]
我記錯組別剛剛把組別改掉。他就說conflict了。不太確定為什麼。

**Pull request merged**
