### PR TITLE
Remove myname.txt and Makefile

### PR DESCRIPTION
**Pull request by JasonChen112101018**

### CODE REVIEW

**Comment by yutingk** [comment]
image

**Comment by yutingk** [comment]
Please remove these file: 
- tests/test_lab3.py  
- oop_lab3_pdb.ipynb

**Comment by JasonChen112101018** [comment]
@yutingk I have remove files and update test_lec9_inheritance.py

**Comment by yutingk** [comment]
Please remove: test.py

**Comment by sunfu-chou** [comment]
@JasonChen112101018 Hi, you deleted the original function `test_coordinate` in tests/test_lec8_classes.py. Don't remove the original function.
Also, you should add your group number to your test functions. Please modify `test_animal` in `tests/test_lec9_inheritance.py`.

**Comment by JasonChen112101018** [comment]
@sunfu-chou Update test_lec8_classes.py and test_lec9_inheritance.py

**Pull request merged**
