### PR TITLE
lec 5 

### PR DESCRIPTION
**Pull request by PinYenChen**
@WuChangJin94 @leowang707

### CODE REVIEW

**Comment by WuChangJin94** [comment]
The following is in the wrong location
lecture3_graph.py
test_digraph.py
test_lect5_tuple.py

tests/test_lect5_tuple.py fails and is named incorrectly

test/team_5 passes

**Comment by PinYenChen** [comment]
@WuChangJin94 @leowang707 dear TAs i have fixed the faults. Thanks

**Comment by leowang707** [comment]
please remove this file:tests/Makefile

**Comment by leowang707** [comment]
fix file name: tests/test_lect5_tuple.py --> tests/test_lec5_tuple.py

remove or move into your own file : tests/test_lab3.py

**Comment by PinYenChen** [comment]
@leowang707 @WuChangJin94 dear TAs i have fixed the errors. THANKS!!!

**Comment by leowang707** [comment]
please remove this file:tests/Makefile

**Comment by PinYenChen** [comment]
@leowang707 i have deleted Makefile in tests folder. Sorry for the error, and i would be aware of the file next time when i push

**Comment by PinYenChen** [comment]
@leowang707 @WuChangJin94

**Pull request merged**
