### PR TITLE
Added docstring and testcode

### PR DESCRIPTION
**Pull request by Xian37**
@wennnny 
@zhuchi76

### CODE REVIEW

**Comment by wennnny** [comment]
Please move all files you pushed into your team_folder!

**Comment by Xian37** [comment]
@wennnny 
@zhuchi76 
I've finished,thanks.

**Comment by Xian37** [comment]
the commit "init" is because
i've met some problems so i copy all the latest file in the repo,and push again to initialize my own repo

**Comment by wennnny** [comment]
sure. but pytest failed with test_city_planner.py. please check your code.
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu/tests/team_9
plugins: xdoctest-1.1.2, profiling-1.7.0, anyio-3.6.2
collected 1 item                                                               

test_city_planner.py F                                                   [100%]

=================================== FAILURES ===================================
______________________________ test_city_planner _______________________________

    def test_city_planner():
    
>       cp = CityPlanner()
E       NameError: name 'CityPlanner' is not defined

test_city_planner.py:7: NameError
=========================== short test summary info ============================
FAILED test_city_planner.py::test_city_planner - NameError: name 'CityPlanner...
============================== 1 failed in 0.06s ===============================

**Comment by Xian37** [comment]
@zhuchi76 @wennnny 
i've fixed it ,thanks

**Comment by zhuchi76** [comment]
Your pytest failed with test_city_planner.py. Fix this error:

(base) tzuchichen@arg10:~/oop-python-nycu/tests/team_9$ pytest test_city_planner.py 
================================================================ test session starts ================================================================
platform linux -- Python 3.11.5, pytest-7.4.0, pluggy-1.0.0
rootdir: /home/tzuchichen/oop-python-nycu/tests/team_9
plugins: anyio-4.2.0
collected 0 items / 1 error                                                                                                                         

====================================================================== ERRORS =======================================================================
_______________________________________________________ ERROR collecting test_city_planner.py _______________________________________________________
../../../anaconda3/lib/python3.11/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
../../../anaconda3/lib/python3.11/site-packages/_pytest/pathlib.py:565: in import_path
    importlib.import_module(module_name)
../../../anaconda3/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1204: in _gcd_import
    ???
<frozen importlib._bootstrap>:1176: in _find_and_load
    ???
<frozen importlib._bootstrap>:1147: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
../../../anaconda3/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
test_city_planner.py:2: in <module>
    from lecture3_graph import *
E     File "/home/tzuchichen/oop-python-nycu/tests/team_9/lecture3_graph.py", line 140
E       Digraph a
E               ^
E   SyntaxError: invalid syntax
============================================================== short test summary info ==============================================================
ERROR test_city_planner.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================= 1 error in 0.06s ==================================================================

**CHATGPT tell me:**

The error you're encountering is due to a syntax mistake in the CityPlanner class initialization within your lecture3_graph.py script. Specifically, the line Digraph a is not valid Python syntax. You likely intended to create an instance of the Digraph class.

Here is how you should correct the CityPlanner class:
class CityPlanner:
    def __init__(self):
        self.g = Digraph()

**This might be helpful!!!**

**Pull request merged**
