### PR TITLE
new test for test_food.py

### PR DESCRIPTION
**Pull request by mattew9410**

### CODE REVIEW

**Comment by mattew9410** [comment]
group 7
＠WuChangJin94＠leowang707

**Comment by mattew9410** [comment]
group 7
@WuChangJin94 @leowang707

**Comment by leowang707** [comment]
please change your file name to your team name

**Comment by leowang707** [comment]
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu/tests/team_7, configfile: pytest.ini
plugins: anyio-3.6.2
collected 2 items                                                              

new_test_greedy.py .F                                                    [100%]

=================================== FAILURES ===================================
_________________________________ test_greedys _________________________________

    def test_greedys():
    
        names = ['wine', 'beer', 'pizza', 'burger', 'fries',
                 'cola', 'apple', 'donut', 'cake', 'steak']
        values = [89, 90, 95, 100, 90, 79, 50, 10, 150, 129]
        calories = [123, 154, 258, 354, 365, 150, 95, 195, 95, 354]
        menu = Menu(names, values, calories)
        foods = menu.get_foods()
    
        max_units = 750
    
        print('Use greedy by value to allocate', max_units,
              'calories')
        taken, val = greedy(foods, max_units, Food.get_value)
        expected_str = Menu.get_foods_str(taken)
>       assert val == 284
E       assert 374.0 == 284

new_test_greedy.py:39: AssertionError
----------------------------- Captured stdout call -----------------------------
Use greedy by value to allocate 750 calories
=========================== short test summary info ============================
FAILED new_test_greedy.py::test_greedys - assert 374.0 == 284
========================= 1 failed, 1 passed in 0.06s ==========================


============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu/tests/team_7, configfile: pytest.ini
plugins: anyio-3.6.2
collected 2 items                                                              

new_test_menu.py F.                                                      [100%]

=================================== FAILURES ===================================
__________________________________ test_menu ___________________________________

    def test_menu():
        names = ["apple", "banana", "orange","guava"]
        values = [10, 20, 30, 900]
        calories = [50, 100, 150, 150]
        expected_foods = [
            Food("apple", 10, 50),
            Food("banana", 20, 100),
            Food("orange", 30, 150),
            Food("guava", 900, 150),
        ]
        menu = Menu(names, values, calories)
        foods = menu.get_foods()
    
        print(menu)
    
        assert foods[0].get_cost() == expected_foods[0].get_cost()
        assert foods[1].get_value() == expected_foods[1].get_value()
>       assert Menu.get_foods_str(foods) == \
            'apple: <10, 50>; banana: <20, 100>; orange: <30, 150>; '
E       AssertionError: assert 'apple: <10, ... <900, 150>; ' == 'apple: <10, ...: <30, 150>; '
E         Skipping 44 identical leading characters in diff, use -v to show
E         - <30, 150>; 
E         + <30, 150>; guava: <900, 150>;

new_test_menu.py:24: AssertionError
----------------------------- Captured stdout call -----------------------------
apple: <10, 50>; banana: <20, 100>; orange: <30, 150>; guava: <900, 150>; 
=========================== short test summary info ============================
FAILED new_test_menu.py::test_menu - AssertionError: assert 'apple: <10, ... ...
========================= 1 failed, 1 passed in 0.06s ==========================

**Comment by mattew9410** [comment]
@WuChangJin94 @leowang707  助教您好，我修改好檔案了。

**Pull request merged**
