### PR TITLE
Group9 adding test_food.py

### PR DESCRIPTION
**Pull request by Xian37**

### CODE REVIEW

**Comment by Xian37** [comment]
@zhuchi76 
i run the pytest on test_food.py
and it shows:
================================================================================================== ERRORS ==================================================================================================
______________________________________________________________________________________ ERROR collecting test_food.py _______________________________________________________________________________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_9/test_food.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_food.py:3: in <module>
    from mit_ocw_data_science.lec2.menu import Food
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'





mit_ocw_data_science actually exists but it give error and i dont know how to fix it, thanks.

**Comment by Xian37** [comment]
@zhuchi76 
i've fixed the test_food.py and it pass the pytest, thanks

**Comment by Xian37** [comment]
@zhuchi76 @wennnny 
i've passed the pytest on test_fib.py and test_food.py ,Thanks!

**Comment by wennnny** [comment]
Please remove "fib_9.py" file.

**Comment by Xian37** [comment]
@wennnny @zhuchi76 
I've done,Thanks.

**Pull request merged**
