### PR TITLE
111705015

### PR DESCRIPTION
**Pull request by 1107sammm**

### CODE REVIEW

**Comment by sunfu-chou** [comment]
Please delete myname.txt before you create a pull request.
Run `git rm myname.txt` and then commit it.

**Comment by uwe77** [comment]
you have a failed at:
test_lec8_classes.py::test_coordinate PASSED
test_lec8_classes.py::test_intset PASSED
test_lec8_classes.py::test_5_frac PASSED
test_lec8_classes.py::test_8_coordinate PASSED
test_lec8_classes.py::test_16_coordinate FAILED
test_lec8_classes.py::test_8_intset PASSED
test_lec8_classes.py::test_13_coordinate PASSED
test_lec8_classes.py::test_17_coordinate PASSED
test_lec8_classes.py::test_17_intset PASSED
test_lec8_classes.py::test_1_coordinate PASSED
test_lec8_classes.py::test_1_intset PASSED
test_lec8_classes.py::test_6_coordinate PASSED
test_lec8_classes.py::test_14_coordinate PASSED
test_lec8_classes.py::test_9_coordinate PASSED
test_lec8_classes.py::test_9_intset PASSED

**Comment by 1107sammm** [comment]
@sunfu-chou

**Comment by sunfu-chou** [comment]
Hi @1107sammm ,
You can see Files changed: 5 on the top of this page.
The files you can push are:
1. tests/test_lecX_YYY.py
2. tests/team_ZZ/test_your_files.py
Don't push other files.
Please ensure you clean up the code before you commit and continue this pull request again.
Also, you forget to push `add_path.py`

**Comment by 1107sammm** [comment]
@sunfu-chou 
Sorry, I got confused, would you prefer tell me what should I do exactly to meet your requirement? Thanks!!!

**Comment by sunfu-chou** [comment]
@1107sammm 
You can see this [#56 Files changed](https://github.com/ARG-NCTU/oop-python-nycu/pull/56/files).
You push `Makefile` and `tests/test_lab3.py`. However, they should not be pushed.
Please `git rm path/to/the/files` to delete them.

**Comment by 1107sammm** [comment]
@sunfu-chou

**Comment by sunfu-chou** [comment]
Pytest failed after merged:
```
==================================================================================================== FAILURES =====================================================================================================
_________________________________________________________________________________________________ test_16_rabbit __________________________________________________________________________________________________

    def test_16_rabbit():
        r1 = inh.Rabbit(3)
        r2 = inh.Rabbit(4)
        r3 = inh.Rabbit(5)
        r4 = r1 + r2
        r5 = r3 + r4
        r6 = r4 + r3
        assert r1.get_age() == 3
        assert r2.get_age() == 4
        assert r3.get_age() == 5
>       assert r1.get_rid() == "007"
E       AssertionError: assert '021' == '007'
E         - 007
E         + 021

test_lec9_inheritance.py:370: AssertionError
============================================================================================= short test summary info =============================================================================================
FAILED test_lec9_inheritance.py::test_16_rabbit - AssertionError: assert '021' == '007'
========================================================================================== 1 failed, 25 passed in 0.04s ===========================================================================================
```
image

HINT: Be careful when calling `get_rid()`. Why?

**Comment by 1107sammm** [comment]
@sunfu-chou

**Comment by 1107sammm** [comment]
@sunfu-chou

**Pull request merged**
