### PR TITLE
lec8_testing code

### PR DESCRIPTION
**Pull request by lonea2005**

### CODE REVIEW

**Comment by sunfu-chou** [comment]
Please delete unrelated files (*.txt).

**Comment by lonea2005** [comment]
@sunfu-chou 
file deleted

**Comment by lonea2005** [comment]
@sunfu-chou 
files deleted
only related files now
thanks

**Comment by sunfu-chou** [comment]
lec8, lec9, lec12 is passed.
However, Don't push `tests/test_lab3.py` and `tests/test_lec13_Graph.py`. Please `git rm` to remove them.

**Comment by lonea2005** [comment]
files removed

**Comment by lonea2005** [comment]
@sunfu-chou files removed

**Comment by sunfu-chou** [comment]
@lonea2005 
`tests/team_16/test_16_food.py`, `tests/team_16/test_16_greedy.py`, `tests/team_16/test_16_max_value.py`, `tests/team_16/test_16_menu.py` hav passed.

However, you need to remove `lab7_Exercise.ipynb` using `git rm`.

Also, `tests/team_16/test_lec4.py` contains unmerged content like
```
<<<<<<< HEAD
=======

>>>>>>> 8f98e466692ee5608fecff958baf8afab16b3052
```
Please modify `tests/team_16/test_lec4.py`

**Comment by lonea2005** [comment]
@sunfu-chou 
完成檔案 merge 了

**Comment by sunfu-chou** [comment]
大部分的code看起來是final project的，建議你們開一個final的repo來存哦
先關閉這個PR

**Pull request closed without merging**
