### PR TITLE
group4 lec9

### PR DESCRIPTION
**Pull request by lawxiuyong**

### CODE REVIEW

**Comment by lawxiuyong** [comment]
@phoebeliu123 
@uwe77

**Comment by phoebeliu123** [comment]
please use `git rm` to remove "myname.txt".

**Comment by lawxiuyong** [comment]
> please use `git rm` to remove "myname.txt".

done

**Comment by phoebeliu123** [comment]
please also remove the `tests/group4_test_lec9.py` file. Your commit should only include the modification of `tests/test_lec8_classes.py` and `tests/test_lec9_inheritance.py`.

**Comment by lawxiuyong** [comment]
> please also remove the `tests/group4_test_lec9.py` file. Your commit should only include the modification of `tests/test_lec8_classes.py` and `tests/test_lec9_inheritance.py`.

done

**Pull request closed without merging**
