### PR TITLE
group2 add test_2_Menu and path

### PR DESCRIPTION
**Pull request by cookieeikooc**

### CODE REVIEW

**Comment by uwe77** [comment]
please move "group2/" into "tests/", like: tests/group2/"other file"

**Comment by uwe77** [comment]
and remenber to tag 小天使1&2

**Comment by cookieeikooc** [comment]
@uwe77, 改路徑了！！

**Comment by uwe77** [comment]
@cookieeikooc 
I suggest using the same repo with your team as it's more convenient for collaborative editing, PR, or debugging.

**Pull request merged**
