### PR TITLE
team_11_update

### PR DESCRIPTION
**Pull request by s100179**
@wennnny
@zhuchi76

### CODE REVIEW

**Comment by zhuchi76** [comment]
Which is your group main account: **kingblue5453** or **s100179** ?

**Comment by kingblue5453** [comment]
kingblue5453

**Comment by zhuchi76** [comment]
root@arg10:~/oop-python-nycu/tests/team_11# pytest
=============================================================== test session starts ================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu/tests/team_11
plugins: xdoctest-1.1.2, profiling-1.7.0, anyio-3.6.2
collected 7 items / 9 errors                                                                                                                       

====================================================================== ERRORS ======================================================================
_________________________________________________________ ERROR collecting test_11_food.py _________________________________________________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_11_food.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_11_food.py:3: in <module>
    from mit_ocw_data_science.lec2.menu import Food
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
________________________________________________________ ERROR collecting test_11_greedy.py ________________________________________________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_11_greedy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_11_greedy.py:4: in <module>
    from mit_ocw_data_science.lec2.menu import *
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
_________________________________________________________ ERROR collecting test_11_lec4.py _________________________________________________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_11_lec4.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_11_lec4.py:4: in <module>
    from lec4_module import roll_die, run_sim, same_date, birthday_prob
E   ModuleNotFoundError: No module named 'lec4_module'
______________________________________________________ ERROR collecting test_11_max_value.py _______________________________________________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_11_max_value.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_11_max_value.py:4: in <module>
    from mit_ocw_data_science.lec2.menu import *
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
_________________________________________________________ ERROR collecting test_11_menu.py _________________________________________________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_11_menu.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_11_menu.py:4: in <module>
    from mit_ocw_data_science.lec2.menu import *
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
__________________________________________________________ ERROR collecting test_food.py ___________________________________________________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_food.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_food.py:3: in <module>
    from mit_ocw_data_science.lec2.menu import Food
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
_________________________________________________________ ERROR collecting test_greedy.py __________________________________________________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_greedy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_greedy.py:4: in <module>
    from mit_ocw_data_science.lec2.menu import *
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
________________________________________________________ ERROR collecting test_max_value.py ________________________________________________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_max_value.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_max_value.py:4: in <module>
    from mit_ocw_data_science.lec2.menu import *
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
__________________________________________________________ ERROR collecting test_menu.py ___________________________________________________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_menu.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_menu.py:4: in <module>
    from mit_ocw_data_science.lec2.menu import *
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
============================================================= short test summary info ==============================================================
ERROR test_11_food.py
ERROR test_11_greedy.py
ERROR test_11_lec4.py
ERROR test_11_max_value.py
ERROR test_11_menu.py
ERROR test_food.py
ERROR test_greedy.py
ERROR test_max_value.py
ERROR test_menu.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 9 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================ 9 errors in 0.05s =================================================================

**Please fix these errors and push again**

**Comment by kingblue5453** [comment]
@wennnny

**Comment by wennnny** [comment]
there are almost the same errors

root@wen-Victus:~/oop-python-nycu/tests# pytest team_11
=========================== test session starts ===========================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu/tests
plugins: xdoctest-1.1.2, profiling-1.7.0, anyio-3.6.2
collected 9 items / 5 errors / 4 selected                                 

================================= ERRORS ==================================
__________________ ERROR collecting team_11/test_food.py __________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_food.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
team_11/test_food.py:3: in <module>
    from mit_ocw_data_science.lec2.menu import Food
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
_________________ ERROR collecting team_11/test_greedy.py _________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_greedy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
team_11/test_greedy.py:4: in <module>
    from mit_ocw_data_science.lec2.menu import *
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
__________________ ERROR collecting team_11/test_lec4.py __________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_lec4.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
team_11/test_lec4.py:4: in <module>
    from lec4_module import roll_die, run_sim, same_date, birthday_prob
E   ModuleNotFoundError: No module named 'lec4_module'
_______________ ERROR collecting team_11/test_max_value.py ________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_max_value.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
team_11/test_max_value.py:4: in <module>
    from mit_ocw_data_science.lec2.menu import *
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
__________________ ERROR collecting team_11/test_menu.py __________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/team_11/test_menu.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
team_11/test_menu.py:4: in <module>
    from mit_ocw_data_science.lec2.menu import *
E   ModuleNotFoundError: No module named 'mit_ocw_data_science'
========================= short test summary info =========================
ERROR team_11/test_food.py
ERROR team_11/test_greedy.py
ERROR team_11/test_lec4.py
ERROR team_11/test_max_value.py
ERROR team_11/test_menu.py
!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!
============================ 5 errors in 0.39s ============================

**Comment by kingblue5453** [comment]
請問什麽是錯誤的python名稱？ 我們之前有問過一個助教，說是不要更動原本test的名子，所以我們都有把名子改回來。請問這個錯誤是指什麽意思？謝謝


wen ***@***.***> 於 2024年5月20日 週一 下午4:01寫道：

**Pull request merged**
