### PR TITLE
lec3＆lec4

### PR DESCRIPTION
**Pull request by benjaminpot**

### CODE REVIEW

**Comment by benjaminpot** [comment]
@WuChangJin94 
@leowang707

**Comment by leowang707** [comment]
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu
plugins: anyio-3.6.2
collected 25 items / 2 errors / 23 selected                                    

==================================== ERRORS ====================================
__________ ERROR collecting tests/team_8/lec3_1/test_city_planner.py ___________
import file mismatch:
imported module 'test_city_planner' has this __file__ attribute:
  /home/arg/oop-python-nycu/tests/team_8/test_city_planner.py
which is not the same as the test file we want to collect:
  /home/arg/oop-python-nycu/tests/team_8/lec3_1/test_city_planner.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_____________ ERROR collecting tests/team_8/lec3_1/test_digraph.py _____________
import file mismatch:
imported module 'test_digraph' has this __file__ attribute:
  /home/arg/oop-python-nycu/tests/team_8/test_digraph.py
which is not the same as the test file we want to collect:
  /home/arg/oop-python-nycu/tests/team_8/lec3_1/test_digraph.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=========================== short test summary info ============================
ERROR tests/team_8/lec3_1/test_city_planner.py
ERROR tests/team_8/lec3_1/test_digraph.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 0.05s ===============================

**Comment by leowang707** [comment]
======================================== test session starts ========================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/arg/oop-python-nycu
plugins: anyio-3.6.2
collected 25 items / 2 errors / 23 selected                                                         

============================================== ERRORS ===============================================
_____________________ ERROR collecting tests/team_8/lec3_1/test_city_planner.py _____________________
import file mismatch:
imported module 'test_city_planner' has this __file__ attribute:
  /home/arg/oop-python-nycu/tests/team_8/test_city_planner.py
which is not the same as the test file we want to collect:
  /home/arg/oop-python-nycu/tests/team_8/lec3_1/test_city_planner.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_______________________ ERROR collecting tests/team_8/lec3_1/test_digraph.py ________________________
import file mismatch:
imported module 'test_digraph' has this __file__ attribute:
  /home/arg/oop-python-nycu/tests/team_8/test_digraph.py
which is not the same as the test file we want to collect:
  /home/arg/oop-python-nycu/tests/team_8/lec3_1/test_digraph.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
====================================== short test summary info ======================================
ERROR tests/team_8/lec3_1/test_city_planner.py
ERROR tests/team_8/lec3_1/test_digraph.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 2 errors in 0.05s =========================================

**Comment by benjaminpot** [comment]
@WuChangJin94 
@leowang707 
We have fixed the error and completed the practice for lec4. Thanks!

**Pull request merged**
