### PR TITLE
add new food test

### PR DESCRIPTION
**Pull request by PinYenChen**

### CODE REVIEW

**Comment by PinYenChen** [comment]
@leowang707 @WuChangJin94

**Comment by WuChangJin94** [comment]
=================================== ERRORS ====================================
________________ ERROR collecting tests/test_5/test_5_food.py _________________
ImportError while importing test module '/home/arg/oop-python-nycu/tests/test_5/test_5_food.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_5/test_5_food.py:2: in <module>
    import add_path
E   ModuleNotFoundError: No module named 'add_path'
=========================== short test summary info ===========================
ERROR tests/test_5/test_5_food.py
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!

**Comment by leowang707** [comment]
sry, please change your file name to "team_5" and pull request again.

**Comment by PinYenChen** [comment]
助教您好：
因為在Test 檔案裡已經有Team_5的檔案夾，所以名字改不了，那這樣的話要怎麼處理。
謝謝助教
品妍敬上

leowang707 ***@***.***> schrieb am Mo. 1. Apr. 2024 um 7:27
PM:

**Comment by sunfu-chou** [comment]
Hi @PinYenChen,

請你將檔名統一成 `tests/team_5/test_food.py`

1. 把你寫的 `tests/test_5/test_5_food.py` 的內容貼到 `tests/team_5/test_food_5.py`
2. 重新命名成 `tests/team_5/test_food.py`
3. 再把錯誤的檔案刪掉

做完這些就能再提一次 PR 哦

**Pull request merged**
